- places:
  - name: "the Bronx"
    special_place: "the loanshark"
  - name: "Manhattan"
    special_place: "the bank"
  - name: "Central Park"
    special_place: "the hospital"
  - name: "Coney Island"
  - name: "Staten Island"
  - name: "Queens"
  - name: "Brooklyn"
    special_place: "Dan's House of Guns"
  - name: "the Ghetto"
    special_place: "the pub"

- drugs:
  - name: "Hashish"
  - name: "Heroin"
  - name: "Ludes"
  - name: "Opium"
  - name: "PCP"
  - name: "Peyote"
  - name: "Shrooms"
  - name: "Speed"
  - name: "Weed"
  - name: "Acid"
  - name: "Ecstasy"

- weapons:
  - type: "Fist"
    damage: 1
    cost: 0
    level: 1
  - type: "Brass Knuckle"
    damage: 2
    cost: 1000
    level: 3
  - type: "Knife"
    damage: 3
    cost: 5000
    level: 6
  - type: "Gun"
    damage: 4
    cost: 10000
    level: 12
